### PR TITLE
Add "exclude ARPing" option

### PR DESCRIPTION
**Pull request by bewee**

### CODE REVIEW

**Comment by bewee** [comment]
(Would have liked to link #34 but cannot)

**Comment by bewee** [comment]
Anything wrong with this PR?🙈

**Comment by flatsiedatsie** [comment]
It's too minimal and doesn't have safety checks. I'm also not a fan of doing it this way. I may add a "use ping only" option.

**Comment by bewee** [comment]
Ok then. Although I could have added additional safety checks if this had been the only problem and you had told me😅

> I may add a "use ping only" option.

I don't know how exactly different you may want to do this. But I think it would be quite useful if this could be set on a per-device basis rather than just being one single global option. For instance, I do use the arping for my mobile phone (since it's pretty damn good working) - just not for the desktop :)

**Comment by flatsiedatsie** [comment]
Sorry for the delay, this feature has now been incorporated.

**Pull request closed without merging**
